/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Box.gltf 
Author: Artem Goyko (https://sketchfab.com/Artem.Goyko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/box-3c8b08023b61484aa583994da991274c
Title: Box
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Box = (props)=> {
  const { nodes, materials } = useGLTF('./model/box/Box.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.None} rotation={[Math.PI / 2, 0, 0]} scale={50} />
      </group>
    </group>
  )
}

useGLTF.preload('/Box.gltf')

export default Box;