/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Box2.gltf 
Author: Nata Gabbiano (https://sketchfab.com/natagabbiano)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cardboard-box-c03fd62713a14760b187defa6ad79c6e
Title: Cardboard box
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const NewBox = (props) => {
  const { nodes, materials } = useGLTF('./model/NewBox/Box2.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Cube001__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={1200} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/NewBox/Box2.gltf')

export default NewBox;